Repository jellyfin/jellyfin-ios, pull requests merged in 2024-11, with the labels that each got.

#541 Remove unavailable Expo version
  components/AppInfoFooter.js
  components/__tests__/AppInfoFooter.test.js
  langs/en.json
  screens/__tests__/__snapshots__/SettingsScreen.test.js.snap
Labels: cleanup

#544 Remove reddit and old project references from README
  README.md
Labels: documentation

#545 Remove 10.7 warning for native player setting
  langs/en.json
  screens/SettingsScreen.js
  screens/__tests__/__snapshots__/SettingsScreen.test.js.snap
Labels: cleanup

#546 Enable fmp4 by default for native player
  stores/SettingStore.js
  stores/__tests__/SettingStore.test.js
Labels: enhancement

#547 Patch metro config to fix invalid native module urls
  metro.config.js
Labels: build

#430 Don't require full screen on iOS
  app.json
Labels: bug

#548 Enable renovate dashboard
  .github/renovate.json
Labels: dependencies

#543 Update to latest Expo 46 version
  index.js
  ios/.gitignore
  ios/.xcode.env
  ios/Jellyfin.xcodeproj/project.pbxproj
  ios/Jellyfin.xcodeproj/xcshareddata/xcschemes/Jellyfin.xcscheme
  ios/Jellyfin.xcworkspace/contents.xcworkspacedata
  ios/Jellyfin/AppDelegate.h
  ios/Jellyfin/AppDelegate.mm
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-20x20@1x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-20x20@2x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-20x20@3x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-29x29@1x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-29x29@2x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-29x29@3x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-40x40@1x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-40x40@2x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-40x40@3x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-60x60@2x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-60x60@3x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-76x76@1x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-76x76@2x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/App-Icon-83.5x83.5@2x.png
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/Jellyfin/Images.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png
  ios/Jellyfin/Images.xcassets/Contents.json
  ios/Jellyfin/Images.xcassets/SplashScreen.imageset/Contents.json
  ios/Jellyfin/Images.xcassets/SplashScreen.imageset/image.png
  ios/Jellyfin/Images.xcassets/SplashScreenBackground.imageset/Contents.json
  ios/Jellyfin/Images.xcassets/SplashScreenBackground.imageset/image.png
  ios/Jellyfin/Info.plist
  ios/Jellyfin/Jellyfin.entitlements
  ios/Jellyfin/SplashScreen.storyboard
  ios/Jellyfin/Supporting/Expo.plist
  ios/Jellyfin/main.m
  ios/Jellyfin/noop-file.swift
  ios/Podfile
  ios/Podfile.lock
  ios/Podfile.properties.json
  package-lock.json
  package.json
  patches/xcode15.patch
Labels: build

#556 Update expo managed dependencies in renovate config
  .github/renovate.json
Labels: dependencies

#557 Update app permissions and platforms
  app.json
  ios/Jellyfin.xcodeproj/project.pbxproj
  ios/Jellyfin/Info.plist
  package.json
Labels: bug, build

#562 Bump versions for 1.6.0
  app.json
  ios/Jellyfin/Info.plist
  package-lock.json
  package.json
Labels: build

#565 Add initial publish action and fastlane
  .github/workflows/publish-beta.yml
  .gitignore
  Gemfile
  Gemfile.lock
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: build

#567 Add automated release notes configuration
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/release.yaml
Labels: build

#570 Replace the add issue link with getting help
  constants/Links.js
  langs/en.json
  screens/__tests__/__snapshots__/SettingsScreen.test.js.snap
Labels: cleanup

#572 Add enhancements section to release notes
  .github/release.yaml
Labels: build

#580 Add audio channels to profile builder options
  assets/js/NativeShell.staticjs
Labels: enhancement

#579 Fix white screen when the content process terminates
  screens/HomeScreen.js
  screens/__tests__/__snapshots__/HomeScreen.test.js.snap
Labels: bug
