Repository jellyfin/jellyfin-ios, pull requests merged in 2024-08, with the labels that each got.

#521 Add .nvmrc
  .nvmrc
Labels: build

#522 fix android version type mismatch
  utils/Device.js
Labels: bug

#525 Use new logos
  App.js
  assets/images/logo-dark.png
  assets/images/logo-light.png
  assets/images/logoblack.png
  assets/images/logowhite.png
  screens/AddServerScreen.js
Labels: enhancement
